showindex:
    path: /{num}
    defaults: { _controller: AppBundle:Index:index, num: 1 }
    requirements:
        num: '\d+'
        
showdummy:
    path: /dummy
    defaults: { _controller: AppBundle:Index:dummy }