showindex:
    path: /
    defaults: { _controller: AppBundle:Index:index }
        
showdashboard:
    path: /set/{id}
    defaults: { _controller: AppBundle:Index:dashboard, id: 0 }
    requirements:
        num: '\d+'
        
showdummy:
    path: /dummy
    defaults: { _controller: AppBundle:Index:dummy }