showindex:
    path: /
    defaults: { _controller: AppBundle:Index:index }
        
showdashboard:
    path: /set/{id}
    defaults: { _controller: AppBundle:Index:dashboard, id: 0 }
    requirements:
        id: '\d+'
        
showdummy:
    path: /dummy
    defaults: { _controller: AppBundle:Index:dummy }    

deletefaucet:
    path: /delete/{id}
    defaults: { _controller: AppBundle:Index:delete }
    requirements:
        id: '\d+'

postindex:
    path: /postindex/{action}
    defaults: { _controller: AppBundle:Index:postIndex, action: 'undefined' }
    requirements:
        action: '\w+'
        
faucetlist:
    path: /faucetlist
    defaults: { _controller: AppBundle:Index:faucetList }    
    